graph TD
    A[我的世界] --> B(链接自我: 精神寄托)
    A --> C(链接他人)
    A --> D(链接外物)

    B --> B1[信仰/情绪]
    B1 --> B1_1(每周去一趟寺庙)

    C --> C1[暂无]

    D --> D1[展会]
    D --> D2[事业]

    D2 --> E1[技术]

    E1 --> E1_1[认证授权服务OIDC: keycloak]
    E1 --> E1_2[AI 助手: Claude Code, QWen]
    E1 --> E1_3[Docker 加速]